### ISSUE TITLE
OpenGL window scaling wrong on fullscreen

### ISSUE THREAD

**Issue by Mikroudz** [CumbersomePack/SmartCanvas#66]
When running with --fullscreen flag Windows might change screen resolution to same as the fullscreen window (1280 x 720). This causes OpenGL content to be scaled wrong.

**Comment by Mikroudz** [comment]
Cannot reproduce this bug on my device (Windows 10 does not change screen resolution as it did on the univ machine)
If someone has this problem try removing line 15 from `core.py`:
`#window_size = (1280, 720)`

**Comment by hengzhang-pro** [comment]
This issue has been reproduced on University Big TV when we do testing. Will try it again with Mikroudz solution.

**Comment by Mikroudz** [comment]
I remember this not working, but try setting windows scaling to 100%. See the image for reference.
![image](https://user-images.githubusercontent.com/23717818/155331888-11c58ce2-838a-46de-9f9e-d247d427b0f4.png)
