### ISSUE TITLE
Small issues with demo installation

### ISSUE THREAD

**Issue by Mikroudz** [CumbersomePack/SmartCanvas#74]
- [x]  Painterly filter crashes if canvas is empty
- [x] Text should be more readable in bright conditions
- [x] Progressbar should be darker
- [x] Text for filter name goes outside of screen

**Comment by Mikroudz** [comment]
See d5075d5

**Comment by Mikroudz** [comment]
- [ ] Count how many time the smartcanvas has been used and print it to command line

**Comment by vtiinanen** [comment]
Can you add a fix to the oil painting to your branch?
replace:
'opencv-python-headless==4.5.3.56',
with
'opencv-contrib-python-headless==4.5.4.60',

**Comment by vtiinanen** [comment]
- [ ] flag to turn image flip off? (the image was mirrored at site)
